In [26]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup # Scraping using Beautiful Soup

req = requests.get("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")

soup = BeautifulSoup(req.content,'lxml')

table = soup.find_all('table')[0]

df = pd.read_html(str(table)) # Making readable in pandas

neighborhood=pd.DataFrame(df[0])

neighborhood

    Postcode           Borough          Neighbourhood
0        M1A      Not assigned           Not assigned
1        M2A      Not assigned           Not assigned
2        M3A        North York              Parkwoods
3        M4A        North York       Victoria Village
4        M5A  Downtown Toronto           Harbourfront
..       ...               ...                    ...
282      M8Z         Etobicoke              Mimico NW
283      M8Z         Etobicoke     The Queensway West
284      M8Z         Etobicoke  Royal York South West
285      M8Z         Etobicoke         South of Bloor
286      M9Z      Not assigned           Not assigned

[287 rows x 3 columns]

In [27]:
neighborhood.replace("Not assigned", np.nan, inplace = True) # relabling all missing data 
neighborhood.head(5)

  Postcode           Borough     Neighbourhood
0      M1A               NaN               NaN
1      M2A               NaN               NaN
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront

In [28]:
neighborhood.dropna(subset=["Borough"], axis=0, inplace=True) # Dropping cells where borough isn't defined
neighborhood.reset_index(drop=True, inplace=True)
neighborhood

    Postcode           Borough             Neighbourhood
0        M3A        North York                 Parkwoods
1        M4A        North York          Victoria Village
2        M5A  Downtown Toronto              Harbourfront
3        M6A        North York          Lawrence Heights
4        M6A        North York            Lawrence Manor
..       ...               ...                       ...
205      M8Z         Etobicoke  Kingsway Park South West
206      M8Z         Etobicoke                 Mimico NW
207      M8Z         Etobicoke        The Queensway West
208      M8Z         Etobicoke     Royal York South West
209      M8Z         Etobicoke            South of Bloor

[210 rows x 3 columns]

In [29]:
neighborhood['Neighbourhood'].replace(np.nan, 'Borough', inplace=True) # Replacing an undefined neighborhood with its borough
neighborhood

    Postcode           Borough             Neighbourhood
0        M3A        North York                 Parkwoods
1        M4A        North York          Victoria Village
2        M5A  Downtown Toronto              Harbourfront
3        M6A        North York          Lawrence Heights
4        M6A        North York            Lawrence Manor
..       ...               ...                       ...
205      M8Z         Etobicoke  Kingsway Park South West
206      M8Z         Etobicoke                 Mimico NW
207      M8Z         Etobicoke        The Queensway West
208      M8Z         Etobicoke     Royal York South West
209      M8Z         Etobicoke            South of Bloor

[210 rows x 3 columns]

In [44]:
Test = neighborhood.groupby(by='Postcode', axis=0, level=None, as_index=True, sort=True, group_keys=True, squeeze=False)
# Sorting by Postcode

In [47]:
Test.first()

              Borough      Neighbourhood
Postcode
M1B       Scarborough              Rouge
M1C       Scarborough     Highland Creek
M1E       Scarborough          Guildwood
M1G       Scarborough             Woburn
M1H       Scarborough          Cedarbrae
...               ...                ...
M9N              York             Weston
M9P         Etobicoke          Westmount
M9R         Etobicoke  Kingsview Village
M9V         Etobicoke     Albion Gardens
M9W         Etobicoke          Northwest

[103 rows x 2 columns]